import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopSearchComponent from "@/components/TopSearchComponent";
import SideBarComponent from "@/components/SideBarComponent";
import ContentComponent from "@/components/ContentComponent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const geistRubik = Geist({
  variable: "--font-geist-rubik",
  subsets: ["latin"],
})
export const metadata = {
  title: "HRD Entertainment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable}  ${geistMono.variable} ${geistRubik.variable} antialiased`}
      >
     {children}

      </body>
    </html>
  );
}
